### PR TITLE
Fix TTY timer rendering when duration length changes

### LINKED ISSUE #13633: [BUG] incorrect timming output pattern when seconds goes to 2 digits
### Description

```
leo@nebulas:/srv/docker/nextcloud
$ docker compose up -d
[+] up 9/9
 ✔ Container nextcloud-coturn    Running                                                                                                                                                 0.0ss
 ✔ Container nextcloud-nats      Running                                                                                                                                                 0.0ss
 ✔ Container nextcloud-janus     Running                                                                                                                                                 0.0ss
 ✔ Container nextcloud-redis     Running                                                                                                                                                 0.0ss
 ✔ Container nextcloud-postgres  Running                                                                                                                                                 0.0ss
 ✔ Container nextcloud-app       Running                                                                                                                                                 0.0ss
 ✔ Container nextcloud-cron      Running                                                                                                                                                 0.0ss
 ✔ Container nextcloud-signaling Started                                                                                                                                                 10.6s
 ✔ Container nextcloud-web       Running                                                                                                                                                 0.0ss

```

Image

note those `0.0ss` outputs, they should be `0.0s`, despite the `10.6s` line grows these columns from 4 to 5 chars

### Steps To Reproduce

1. get a random docker stack with a container takes extra-long time to start/stop
2. run `docker compose up -d`, `docker compose restart`, etc to start/stop the containers in the stack
3. if one container takes 10+ seconds, while one of the others takes less than 10, the issue shows up

### Compose Version

```Text
Docker Compose version 5.1.0
```

### Docker Environment

```Text
Client:
 Version:    29.3.0
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  5.1.0
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 44
  Running: 44
  Paused: 0
  Stopped: 0
 Images: 34
 Server Version: 29.3.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: local
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: dea7da592f5d1d2b7755e3a161be07f43fad8f75.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.19.6-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.61GiB
 Name: nebulas
 ID: b4765f35-f3f5-4f30-ac20-b3b673069c1e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.16.0.0/12, Size: 24
 Firewall Backend: iptables
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MaybeSam05**
**What I did**

- Fixed the TTY progress timer rendering so that when one task has a longer elapsed time (e.g. `10.6s`) and others are shorter (e.g. `0.0s`), the shorter timers correctly overwrite any previous content.
- Normalized the timer column width by padding each timer string to the maximum visible timer length before rendering, preventing artifacts like `0.0ss` from leftover characters.

**Related issue**
Fixes #13633

### CODE REVIEW

File: cmd/display/tty.go [hunk 1]
```diff
@@ -339,6 +339,18 @@ func (w *ttyWriter) printWithDimensions(terminalWidth, terminalHeight int) {
...
 
+	// pad timers so they all have the same visible width
+	for i := range lines {
+		l := &lines[i]
+		if l.timer == "" {
+			continue
+		}
+		timerWidth := utf8.RuneCountInString(l.timer)
+		if timerWidth < timerLen {
+			l.timer = l.timer + strings.Repeat(" ", timerLen-timerWidth)
```
Comment (ndeloof) [inline cmd/display/tty.go]: this should use left-padding to align counter on terminal right

**Comment by MaybeSam05** [comment]
Implemented left-padding for the timer column so the timer aligns on the terminal right edge. Also added a regression test to cover differing timer widths. Thanks @ndeloof.
