### PR TITLE
run.sh: handle unix:// prefix in DOCKER_HOST

### LINKED ISSUE #7281: run.sh fails when DOCKER_HOST is set to unix:///var/run/docker.sock
## Description of the issue

The `run.sh` script doesn't properly bind mount the socket if `DOCKER_HOST` uses the `unix://` prefix for the socket.

`docker`  itself doesn't understand the default (`/var/run/docker.sock`) because it lacks the `unix://` prefix.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
Unable to find image 'docker/compose:1.25.1' locally
1.25.1: Pulling from docker/compose
050382585609: Pulling fs layer
cbdc9ab2244c: Pulling fs layer
ef12b890287b: Pulling fs layer
04731e4f799d: Pulling fs layer
04731e4f799d: Waiting
cbdc9ab2244c: Download complete
050382585609: Verifying Checksum
050382585609: Download complete
050382585609: Pull complete
cbdc9ab2244c: Pull complete
ef12b890287b: Verifying Checksum
ef12b890287b: Download complete
04731e4f799d: Verifying Checksum
04731e4f799d: Download complete
ef12b890287b: Pull complete
04731e4f799d: Pull complete
Digest: sha256:370b5870d310cf48bc7cc21f25cd883ee49698ce55973f276cbbc8ccb7d858e6
Status: Downloaded newer image for docker/compose:1.25.1

docker-compose version 1.25.1, build a82fef0
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Steps to reproduce the issue

1. `export DOCKER_HOST=unix:///var/run/docker.sock`
2.  `docker-compose up`

### Observed result

```sh
+ export DOCKER_HOST=unix:///var/run/docker.sock
+ bash -x ~/bin/docker-compose up -d
+ set -e
+ VERSION=1.25.4
+ IMAGE=docker/compose:1.25.4
+ '[' -z unix:///var/run/docker.sock ']'
+ '[' -S unix:///var/run/docker.sock ']'
+ DOCKER_ADDR='-e DOCKER_HOST -e DOCKER_TLS_VERIFY -e DOCKER_CERT_PATH'
++ pwd
+ '[' /home/docwhat/test '!=' / ']'
++ pwd
++ pwd
+ VOLUMES='-v /home/docwhat/test'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n /a ']'
+ VOLUMES='-v /home/docwhat/test:/home/docwhat/test -v /home/docwhat:/home/docwhat -e HOME'
+ '[' -t 0 ']'
+ DOCKER_RUN_OPTIONS=' -i'
+ grep -q name=userns
+ docker info --format '{{json .SecurityOptions}}'
++ pwd
+ exec docker run --rm -i -e DOCKER_HOST -e DOCKER_TLS_VERIFY -e DOCKER_CERT_PATH -v /home/docwhat/test:/home/docwhat/test -v /home/docwhat:/home/docwhat -e HOME -w /home/docwhat/test docker/compose:1.25.4 up -d
Unable to find image 'docker/compose:1.25.4' locally
1.25.4: Pulling from docker/compose
89d9c30c1d48: Pulling fs layer
eccc02a3b135: Pulling fs layer
7382d3c5d78f: Pulling fs layer
f410c750fbcb: Pulling fs layer
f410c750fbcb: Waiting
eccc02a3b135: Verifying Checksum
eccc02a3b135: Download complete
89d9c30c1d48: Verifying Checksum
89d9c30c1d48: Download complete
f410c750fbcb: Verifying Checksum
f410c750fbcb: Download complete
7382d3c5d78f: Verifying Checksum
7382d3c5d78f: Download complete
89d9c30c1d48: Pull complete
eccc02a3b135: Pull complete
7382d3c5d78f: Pull complete
f410c750fbcb: Pull complete
Digest: sha256:390bdf3da99a622f5c11f4db386dd97f2858db30cfed07d000b867f1fb25b2f7
Status: Downloaded newer image for docker/compose:1.25.4
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

### Expected result

It should work

### PR DESCRIPTION
**Pull request by docwhat**
docker currently requires the `unix://` prefix when pointing `DOCKER_HOST` at a socket.

fixes #7281

Signed-off-by: Christian Höltje <docwhat@gerf.org>

Resolves #7281

### CODE REVIEW

File: script/run/run.sh [hunk 1]
```diff
@@ -21,10 +21,10 @@ IMAGE="docker/compose:$VERSION"
 
 # Setup options for connecting to docker host
 if [ -z "$DOCKER_HOST" ]; then
-    DOCKER_HOST="/var/run/docker.sock"
+    DOCKER_HOST="unix:///var/run/docker.sock"
```
Comment (joakimr-axis) [inline script/run/run.sh:24]: Nothing is expanded here, should be single quotes

DOCKER_HOST='unix:///var/run/docker.sock'

(or, actually, no quotes at all since they are not needed here but preferred by many anyway to clearly indicate that there is a string)

**Comment by docwhat** [comment]
190 day checkin: is this still of interest?

cc: @rumpl @ndeloof @ulyssessouza

**Review by ndeloof — APPROVED** [review]

**Review by ulyssessouza — APPROVED** [review]
LGTM
