### PR TITLE
Fix #10661: docker compose up always kills the containers on second Ctrl-C

### LINKED ISSUE #10661: [BUG] docker compose up not returning shell and erroneously detecting error
### Description

I want to get this issue down now before I forget some details, so apologies if it's a little light on detail. I will update as I reproduce this error for myself.
I'm running a fairly large project with docker compose and am running an issue where `docker compose up -d` and `docker compose up` are not returning the shell properly.

In the case of detached, one of the services is showing an error when I bring it up. When this happenss, the shell is not returned, even with a `CTRL+C`. The only way to exit is the kill the service directly w/ `kill -HUP <PID>`. When I get the shell back, I can attach to the logs and can confirm that the service that showed error has no errors (although this happens if service genuinely errors or now).

In the non-detached case, the services all come up without error and I attach to the output.log correctly. However, if I do a `CTRL-C` here, the services are stopped but I do not get my shell back automatically. I must then repeatedly do `CTRL-C` which results in
```
^Cno container to kill
^CERRO[0026] got 3 SIGTERM/SIGINTs, forcing shutdown  
```

I tried this in in zsh and bash shells, and each of these in xterm and gnome-terminal (xterm-256color).

Three things that might be causing it/ that are different from similar compose files:
- A lot of services in the compose (35)
- Some sections in the yaml are commented out
- Long file paths for volume mounts

### Steps To Reproduce

1. Environment: Ubuntu 20.04.2 LTS, xterm
     - Docker version 24.0.2, build cb74dfc
     - 
2. Run `docker compose up -d` (see psuedo-compose below)**

** I will add to this as I try reproduce with simpler compose files

```
version: '3'

services:

  myproject_pgsql:
    container_name: pgsql_myproject
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./subdir1/subdir2/configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./subdir1/subdir2/data/pgsql:/var/lib/postgresql/data
        #healthcheck:
        #test: ["CMD-SHELL", "pg_isready"]
        #interval: 10s
        #timeout: 5s
        #retries: 5
    networks:
      myproject_network:
        ipv4_address: 172.0.0.200


networks:
  myproject_network:
    external: true
```

### Compose Version

```Text
Docker Compose version v2.18.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 35
  Running: 34
  Paused: 0
  Stopped: 1
 Images: 22
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-43-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.22GiB
 Name: user
 ID: 1e21a719-ab98-48a2-ae2d-154f3e2cd0e2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jsoriano**
**What I did**

Hitting Ctrl-C twice in docker compose up is supposed to immediately kill the containers. 
Kill executed on the second Ctrl-C was filtering containers depending on its state. In some
cases the containers can reach an state for what these filters don't get any container, and
the command hangs while printing `no container to kill`.

Remove this filtering, so it tries to kill any container it finds, independently of their state.

**Related issue**

Fixes https://github.com/docker/compose/issues/10661

### CODE REVIEW

**Comment by ndeloof** [comment]
AFAICT `kill` on a stopped container will fail
```
Error response from daemon: cannot kill container: dafcbcd023c1: container dafcbcd023c1c1bbed6b0a35a7e1e2420129672c327519698ef8cbd644fefd06 is not running
```
would need to ignore such an error, assuming this is the right fix for this race condition

**Comment by jsoriano** [comment]
> AFAICT `kill` on a stopped container will fail
> 
> ```
> Error response from daemon: cannot kill container: dafcbcd023c1: container dafcbcd023c1c1bbed6b0a35a7e1e2420129672c327519698ef8cbd644fefd06 is not running
> ```

You are right, this was briefly showing an error. I have changed the code to use the internal kill method, that doesn't show the progress. And to ignore the returned error.

File: pkg/compose/up.go [hunk 1]
```diff
@@ -119,10 +119,14 @@ func (s *composeService) Up(ctx context.Context, project *types.Project, options
 					gracefulTeardown()
 				} else {
 					eg.Go(func() error {
-						return s.Kill(context.Background(), project.Name, api.KillOptions{
+						// Intentionally ignore errors, for cases where some
+						// of the containers are already stopped.
+						s.kill(context.Background(), project.Name, api.KillOptions{
```
Comment (ndeloof) [inline pkg/compose/up.go:124]: this should not ignore _all_ errors, but only the "not found" one

Comment (jsoriano) [reply pkg/compose/up.go:124]: I don't find a reliable way to distinguish errors here, as they don't seem to be typed. Should I add the check based on the text of the error? I guess it would be to check if the error message contains `is not running`.

Also, with the current code, even if it returns the error, it doesn't seem to be doing anything about it. If the kill fails, the loop is still finished and the command hangs if there are still containers running. I could try to fix this too if I add error handling.

Comment (ndeloof) [reply pkg/compose/up.go:124]: have you tried using `errdefs.IsNotFound(err)` ?

Comment (jsoriano) [reply pkg/compose/up.go]: Thanks! This worked. I also checked `errdefs.IsConflict`, which happens if one of the containers is already stopped.

File: pkg/compose/up.go [hunk 2]
```diff
@@ -117,15 +122,27 @@ func (s *composeService) Up(ctx context.Context, project *types.Project, options
...
 				if first {
 					gracefulTeardown()
-				} else {
-					eg.Go(func() error {
-						return s.Kill(context.Background(), project.Name, api.KillOptions{
-							Services: options.Create.Services,
-							Project:  project,
-						})
-					})
-					return nil
```
Comment (jsoriano) [inline pkg/compose/up.go:127]: I am removing this return, so it is possible now to try to kill the containers again after one kill failed.

Comment (ndeloof) [reply pkg/compose/up.go:127]: This should not be necessary, I hardly can imagine process could survive a SIGKILL
Also I'm not sure about the potential side-effects doing so, so if you don't mind I'd prefer to be conservative here.

Comment (jsoriano) [reply pkg/compose/up.go:127]: Well, indeed hopefully no process is going to survive a SIGKILL :slightly_smiling_face: But this is sending requests to kill containers to the docker daemon through HTTP, so there are other things that could fail in the way.

In any case I agree with being conservative and keep previous behaviour, I will revert this.

**Review by ndeloof — APPROVED** [review]

**Comment by jsoriano** [comment]
@ndeloof thanks for the reviews and the help on this change. Could you also take a look to https://github.com/docker/compose/pull/11719? Thanks!
