### PR TITLE
don't fail down cmd if services with pre_stop hook already stopped/removed

### LINKED ISSUE #12978: [BUG] Compose down fails if container with pre_stop hooks is stopped
### Description

If I run `docker compose down` on a stack that has a service with `pre_stop` hooks and that container is currently stopped, instead of tearing things down, an error occurs blocking the teardown.

Error message: `Error response from daemon: container <ID> is not running`

Ideally, since the container is stopped, the removal should simply occur with the assumption that the pre_stop hooks ran earlier.

### Steps To Reproduce

1. Create a Compose file with a service configured with pre_stop commands
2. Start the stack with `docker compose up -d`
3. Stop the service `docker compose stop <service>`
4. Tear down the stack `docker compose down`
5. See error

### Compose Version

```Text
Docker Compose version v2.37.3-1-g6514c680a
```
(running on manual build from main branch)

### Docker Environment

```Text
Client:
 Version:    28.3.0-rc.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Docker AI Agent - Ask Gordon (Docker Inc.)
    Version:  v1.5.5
    Path:     /Users/account/.docker/cli-plugins/docker-ai
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.25.0-desktop.1
    Path:     /Users/account/.docker/cli-plugins/docker-buildx
  cloud: Docker Cloud (Docker Inc.)
    Version:  v0.3.14
    Path:     /Users/account/.docker/cli-plugins/docker-cloud
  compose: Docker Compose (Docker Inc.)
    Version:  v2.37.3-1-g6514c680a
    Path:     /Users/account/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.41
    Path:     /Users/account/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Docker Inc.)
    Version:  v0.1.9
    Path:     /Users/account/.docker/cli-plugins/docker-desktop
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.29
    Path:     /Users/account/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     /Users/account/.docker/cli-plugins/docker-init
  mcp: Docker MCP Plugin (Docker Inc.)
    Version:  v0.7.1
    Path:     /Users/account/.docker/cli-plugins/docker-mcp
  model: Docker Model Runner (EXPERIMENTAL) (Docker Inc.)
    Version:  v0.1.30
    Path:     /Users/account/.docker/cli-plugins/docker-model
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/account/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.18.1
    Path:     /Users/account/.docker/cli-plugins/docker-scout

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 73
 Server Version: 28.3.0-rc.1
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Discovered Devices:
  cdi: docker.com/gpu=webgpu
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.10.14-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 16
 Total Memory: 7.653GiB
 Name: docker-desktop
 ID: 8559055f-16ea-45ca-9fe3-a168e6debd51
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/account/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by glours**
**What I did**
Check error type returned by engine and continue if the container with `pre_stop` hook is already stopped or removed
Added e2e tests for both `pre_stop` and `post_start` hooks

**Related issue**
fix #12978 

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**
image

### CODE REVIEW

File: pkg/compose/hook.go [hunk 1]
```diff
@@ -52,6 +53,10 @@ func (s composeService) runHook(ctx context.Context, ctr container.Summary, serv
 		AttachStderr: !detached,
 	})
 	if err != nil {
+		// Ignore errors indicating that some containers were already stopped or removed.
```
Comment (ndeloof) [inline pkg/compose/hook.go]: as `runHook` is only used in 2 places, and this applies to the `stopContainer` case, maybe we could check this error in `stopContainer` caller function and avoid a custom extension?
(this will also cover a race conditions where container is removed _after_ exec was created _but_ before  attach/start

Comment (glours) [reply pkg/compose/hook.go]: 👍 done

**Review by ndeloof — APPROVED** [review]
👻
