### PR TITLE
fix: return error on non-ErrNotExist stat failures in Tar.Sync()

### LINKED ISSUE #13654: sync: non-ErrNotExist stat errors silently treated as "copy" in Tar.Sync()
**Location:** internal/sync/tar.go, Sync() function

**Problem:**
The current logic buckets paths into copy vs delete:

    if _, err := os.Stat(p.HostPath); err != nil && errors.Is(err, fs.ErrNotExist) {
        pathsToDelete = append(pathsToDelete, p.ContainerPath)
    } else {
        pathsToCopy = append(pathsToCopy, *p)
    }

Non-NotExist errors (e.g. EACCES, EIO) are silently ignored and the path is 
treated as copyable. This means permission or IO errors don't stop the sync ,
the operation may fail later in a less obvious place with the original cause lost.

**Expected behavior:**
```
    if err == nil {
        pathsToCopy = append(pathsToCopy, *p)
    } else if errors.Is(err, fs.ErrNotExist) {
        pathsToDelete = append(pathsToDelete, p.ContainerPath)
    } else {
        return fmt.Errorf("stat %q: %w", p.HostPath, err)
    }
```

### PR DESCRIPTION
**Pull request by Lidang-Jiang**
## Summary

- Fix silent misclassification of non-`ErrNotExist` stat errors in `Tar.Sync()` (`internal/sync/tar.go`)
- Add unit tests for the three stat outcomes: exists, not-exists, and permission error

The previous two-way branch only checked for `fs.ErrNotExist`. Any other `os.Stat` error (e.g. `EACCES`, `EIO`) fell through to the `else` clause, silently treating the path as copyable. This masked real errors and caused failures downstream with the original cause lost.

The fix restructures the condition into a three-way branch, following the pattern already used by `entriesForPath()` in the same file.

Fixes #13654

## Before / After

<details>
<summary>Before (buggy behavior)</summary>

Non-`ErrNotExist` stat errors are silently treated as "copy":

```
=== Old (buggy) logic ===
  /tmp/before_test_existing.txt → COPY (err=<nil>)
  /no/such/path → DELETE (not exist)
  /tmp/before_test_noaccess/secret.txt → COPY (err=stat /tmp/before_test_noaccess/secret.txt: permission denied)
```

The path with a permission error is incorrectly added to the copy list instead of surfacing the error.

</details>

<details>
<summary>After (fixed behavior)</summary>

Permission errors are now properly returned:

```
=== New (fixed) logic ===
  /tmp/before_test_existing.txt → COPY
  /no/such/path → DELETE
  /tmp/before_test_noaccess/secret.txt → ERROR: stat /tmp/before_test_noaccess/secret.txt: permission denied
```

Unit test output:

```
=== RUN   TestSync_ExistingPath
--- PASS: TestSync_ExistingPath (0.00s)
=== RUN   TestSync_NonExistentPath
--- PASS: TestSync_NonExistentPath (0.00s)
=== RUN   TestSync_StatPermissionError
--- PASS: TestSync_StatPermissionError (0.00s)
=== RUN   TestSync_MixedPaths
--- PASS: TestSync_MixedPaths (0.00s)
PASS
ok  	github.com/docker/compose/v5/internal/sync	0.005s
```

Lint:

```
$ golangci-lint run ./internal/sync/...
0 issues.
```

</details>

## Test plan

- [x] `TestSync_ExistingPath` — existing host path is correctly added to copy list
- [x] `TestSync_NonExistentPath` — missing host path triggers `rm -rf` delete command
- [x] `TestSync_StatPermissionError` — `EACCES` error is returned immediately (skipped on root/Windows)
- [x] `TestSync_MixedPaths` — mix of existing and missing paths handled correctly in one call
- [x] `golangci-lint run ./internal/sync/...` — 0 issues

### CODE REVIEW

File: internal/sync/tar_test.go [hunk 1]
```diff
@@ -0,0 +1,140 @@
...
+	"context"
+	"io"
+	"os"
+	"path/filepath"
+	"runtime"
+	"testing"
+
+	"github.com/moby/moby/api/types/container"
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
```
Comment (glours) [inline internal/sync/tar_test.go]: Sorry but PR #13689 just remove the `testify` library, can update the test to use `gotest.tools/v3` assertions?

Comment (Lidang-Jiang) [reply internal/sync/tar_test.go]: Done, rebased on latest main and migrated all assertions to `gotest.tools/v3` in c86e506.

**Comment by glours** [comment]
@Lidang-Jiang for legal reason you need to sign-off your last commit otherwise I won't be able to merge your PR

**Comment by Lidang-Jiang** [comment]
Done, added `Signed-off-by` to the last commit in 0b25251.
