### PR TITLE
only check the platform of cached image if image found

### LINKED ISSUE #10574: [BUG] New 2.18 releases fails to build images when runnig `up --build`
### Description

This command: `docker compose -f docker-compose-testing.yaml up -d --build` was working properly with 2.17 version.
With 2.18 it returns: `Error: No such image:`

Simplified *compose* and *dockerfile* contents to reproduce:

* `docker-compose-testing.yaml` file contents:

  ```yaml
  services:
    core:
      container_name: Project_Test
      build:
        context: .
        target: base
      image: project_test
      platform: linux/amd64
      environment:
        - MY_ENVARS=my_values
      restart: on-failure
  ```

* `Dockerfile` file contents:

  ```dockerfile
  FROM python:3.10-alpine as base
  WORKDIR /service
  COPY Pipfile* /service/
  RUN pip install --upgrade pip
  RUN pip install --upgrade wheel
  RUN pip install --no-cache-dir pipenv
  RUN pipenv install --deploy
  ```
  
* `pipfile` file contents:
  (Not really required as the problem comes before attempting to build the dockerfile but shared for completeness)
  ```pipfile
  [[source]]
  url = "https://pypi.org/simple"
  verify_ssl = true
  name = "pypi"

  [packages]
  flask = "*"

  [dev-packages]
  mypy = "*"

  [requires]
  python_version = "3.10"
  ```
  

### Steps To Reproduce

Deploy latest version of `docker compose` from repository at a local folder, `my_compose` while keeping the previous installed version on system:

(Or some other way get both versions installed)

```sh
myusername@localhost compose_problem % docker compose version
Docker Compose version v2.17.3
myusername@localhost compose_problem % ./my_compose/docker-compose version
Docker Compose version v2.18.0
```

With the previously shared files run both docker `compose up` command on both versions:
(Without a prior `build`)

```sh
myusername@localhost compose_problem % docker compose version
Docker Compose version v2.17.3

myusername@localhost compose_problem % ./my_compose/docker-compose version
Docker Compose version v2.18.0

myusername@localhost compose_problem % ./my_compose/docker-compose -f docker-compose-testing.yaml up -d --build
Error: No such image:

myusername@localhost compose_problem % docker compose -f docker-compose-testing.yaml up -d --build
[+] Building 1.8s (3/3) FINISHED
 => [internal] load .dockerignore                           0.0s
 => => transferring context: 2B                             0.0s
 => [internal] load build definition from Dockerfile        0.0s
 => => transferring dockerfile: 240B
 ...
```

This example was made on a MAC but same commands -> same behaviour observed on Linux.

### Compose Version

```Text
Docker Compose version v2.18.0
```

### Docker Environment

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by glours**
**What I did**
Fix build issue introduced in Compose `v2.18.0` when checking local cached image platform (see #10546)

**Related issue**
Fixes #10574

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**

### CODE REVIEW

File: pkg/compose/build.go [hunk 1]
```diff
@@ -251,27 +251,26 @@ func (s *composeService) getLocalImagesDigests(ctx context.Context, project *typ
...
-				OS:           inspect.Os,
-				Variant:      inspect.Variant,
-			}
-			if !platforms.NewMatcher(platform).Match(actual) {
-				return nil, errors.Errorf("image with reference %s was found but does not match the specified platform: wanted %s, actual: %s",
-					imgName, platforms.Format(platform), platforms.Format(actual))
-			}
-		}
-
 		if ok {
```
Comment (ndeloof) [inline pkg/compose/build.go:254]: if !ok { continue } to avoid more indents

**Review by ndeloof — APPROVED** [review]
LGTM
minor readability suggestion
