### PR TITLE
pass All option to backend api.Service when length statuses is not equal to zero

### LINKED ISSUE #11464: [BUG] `docker compose ps --status` behavior differs from documentation
### Description

When looking for exited containers by status, containers do not show up unless I also pass the `--all` flag.

```
$ docker compose ps --status=exited | wc -l
1

$ docker compose ps --all --status=exited | wc -l
7
```

This is in conflict with what I see in the docs:

```
docker compose ps --status=exited
NAME            IMAGE     COMMAND           SERVICE    CREATED         STATUS          PORTS
example-bar-1   alpine    "/entrypoint.â¦"   bar        4 seconds ago   exited (0)
```

### Steps To Reproduce

Given the following `docker-compose.yml`:
```
version: "3"
services:
  ls:
    image: alpine:latest
    command: "ls"
```

Run the following commands and observe the output:

```
$ docker-compose up -d
## output truncated

$ docker compose ps
NAME      IMAGE     COMMAND   SERVICE   CREATED   STATUS    PORTS

$ docker compose ps --all
NAME                   IMAGE           COMMAND   SERVICE   CREATED          STATUS                      PORTS
docker-ps-repro-ls-1   ubuntu:latest   "ls"      ls        15 seconds ago   Exited (0) 13 seconds ago

$ docker compose ps --status=exited
NAME      IMAGE     COMMAND   SERVICE   CREATED   STATUS    PORTS

$ docker compose ps --status=exited --all
NAME                   IMAGE           COMMAND   SERVICE   CREATED          STATUS                      PORTS
docker-ps-repro-ls-1   ubuntu:latest   "ls"      ls        36 seconds ago   Exited (0) 34 seconds ago
```

### Compose Version

```Text
Docker Compose version v2.24.3-desktop.1
```

### Docker Environment

```Text
Client:
 Version:    25.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     /usr/local/lib/docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /usr/local/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout
WARNING: Plugin "/usr/local/lib/docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /usr/local/lib/docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 28
  Running: 20
  Paused: 0
  Stopped: 8
 Images: 98
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 31.3GiB
 Name: docker-desktop
 ID: 1fdd7e93-a030-4ecb-bc9d-463f4b845867
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Anything else?

Tested in WSL (Ubuntu 20.04.6 LTS) and PowerShell on the same machine (Windows 11).

### PR DESCRIPTION
**Pull request by 1arp**
**What I did**
For ps command: Aligned --status=exited behaviour with the documentation.
https://docs.docker.com/engine/reference/commandline/compose_ps/#status

The compose service internally calls docker cli client which lists only running containers by default unless the `all` flag is passed. 

With the change the all flag is passed when the statuses includes `exited`.

**Related issue**

Fixes #11464

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**
image

### CODE REVIEW

**Comment by 1arp** [comment]
I am not sure if the issue is the code or the documentation. The PR addresses the issue in the code but the issue could also be the documentation. :)

**Comment by 1arp** [comment]
@ndeloof would appreciate if you could take a look here

File: cmd/compose/ps.go [hunk 1]
```diff
@@ -113,7 +113,7 @@ func runPs(ctx context.Context, dockerCli command.Cli, backend api.Service, serv
 
 	containers, err := backend.Ps(ctx, name, api.PsOptions{
 		Project:  project,
-		All:      opts.All,
+		All:      opts.All || containsStatus(opts.Status, "exited"),
```
Comment (ndeloof) [inline cmd/compose/ps.go:116]: AFAICT as long as we filter by status we can force `All`, as irrelevant containers will anyway be filtered

**Review by ndeloof — APPROVED** [review]
LGMT, could be simplified by just forcing `All` when a status filter is selected

File: cmd/compose/ps.go (hunk 1 above)
Comment (1arp) [reply cmd/compose/ps.go:116]: You are right but incase where users explicitly set it to false we will not be able to see the exited containers.
IMO either we should throw an error in these cases or have the default behaviour as in the change.
Open to your opinion on this.

Comment (ndeloof) [reply cmd/compose/ps.go:116]: `opts.All || opts.Status != ""` sounds enough to me. We could check `--all` flag was not intentionally set to `false` in command `PreRun` to prevent misuse, but as a corner case with no benefit I wouldn't worry about it

**Comment by 1arp** [comment]
@ndeloof CAn you please rerun the tests, seems like there was a timeout while getting the docker image.
