### PR TITLE
as --no-build is set, set service image to default image name

### LINKED ISSUE #8785: Can't use --no-build with services with a build section
When using `docker compose up --no-build` a check is done to ensure either `image` or `build` exists in a service: https://github.com/docker/compose/blob/7365917244ea791d304d5284a706aff09965636e/pkg/compose/build.go#L98 called from https://github.com/docker/compose/blob/ef786f9245eef1759c1b6da2661a2703b243fb54/pkg/compose/create.go#L66

However as the `build` section is removed in `createOptions.Apply` when `--no-build` is specified https://github.com/docker/compose/blob/7c47673d4af41d79900e6c70bc1a3f9f17bdd387/cmd/compose/create.go#L117

This means that `docker compose up --no-build` always fails even if you've ensured these images have been built.

Full repro here: https://github.com/z0w13/docker-compose-no-build-repro

**Output of `docker compose version`:**

```
Docker Compose version 2.0.1
```

The behaviour in 1.x was (in my opinion) correct, failing if the image hasn't been preivously built and otherwise succeeding:

```
docker-compose up --no-build
ERROR: Service 'repro' needs to be built, but --no-build was passed.
```

```
docker-compose build
  Building repro
  [+] Building 0.0s (3/3) FINISHED
   => [internal] load build definition from Dockerfile
  0.0s => => transferring dockerfile: 31B
    0.0s => [internal] load .dockerignore
  0.0s => => transferring context: 2B
  0.0s => exporting to image
  0.0s => => writing image sha256:78f8bb0557f61538b4fbb173d0ca3a8f466d77cfeee0c62a1a6f969288eeff6b
  0.0s => => naming to docker.io/library/repro_repro
docker-compose up --no-build
  Creating repro_repro_1 ...
```

### PR DESCRIPTION
**Pull request by ndeloof**
**What I did**
when `--no-build` is set, enforce service image to have a value, using default image name logic.

**Related issue**
close #8785

### CODE REVIEW

File: pkg/api/api.go [hunk 1]
```diff
@@ -445,3 +445,12 @@ const (
 	// UserCancel user cancelled compose up, we are stopping containers
 	UserCancel
 )
+
+// GetDefaultImageName computes the default image name for a service, used to tag built images
+func GetDefaultImageName(service types.ServiceConfig, projectName string) string {
+	imageName := service.Image
+	if imageName == "" {
+		imageName = projectName + "_" + service.Name
```
Comment (milas) [inline pkg/api/api.go:453]: @glours Should we make this `-` to align with other resources (compose-spec/compose-go#294)?

Comment (milas) [reply pkg/api/api.go:453]: Oh, I see this is actually not a change in this PR, as this logic existed perviously as `getImageName` and is just exported now, so don't need to address before merging this even if we want to change

File: pkg/api/api.go [hunk 2]
```diff
@@ -445,3 +445,12 @@ const (
 	// UserCancel user cancelled compose up, we are stopping containers
 	UserCancel
 )
+
+// GetDefaultImageName computes the default image name for a service, used to tag built images
+func GetDefaultImageName(service types.ServiceConfig, projectName string) string {
```
Comment (milas) [inline pkg/api/api.go:450]: I'd propose renaming this to `GetImageNameOrDefault` since it reads `service.Image` if populated and then falls back to producing one. Particularly now that it's exported 😉

**Review by milas — CHANGES_REQUESTED** [review]
I think the exported function should be renamed as it's a bit misleading right now, but otherwise LGTM

File: pkg/api/api.go (hunk 1 above)
Comment (glours) [reply pkg/api/api.go:453]: It's less important for the image name, but I'll add a commit to use the compose separator 👍

Comment (glours) [reply pkg/api/api.go:453]: I'll do it in a PR to fix this issue #9618

**Review by milas — APPROVED** [review]
🚀
