### PR TITLE
fix provider concurrent environment map accesses

### LINKED ISSUE #12937: concurrent map write by provider
### Description

happens when a service depends on 2 or more services with providers
https://github.com/docker/compose/blob/ea48480d809a03e4abe0a81f69be66bf7b85bcd9/pkg/compose/plugins.go#L77

### Steps To Reproduce

_No response_

### Compose Version

```Text

```

### Docker Environment

```Text

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by glours**
**What I did**
Add mutex to fix concurrent map access to environment configuration when a service depends on multiple provider services

**Related issue**
fix #12937 

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**
image

### CODE REVIEW

File: pkg/compose/plugins.go [hunk 1]
```diff
@@ -70,6 +74,8 @@ func (s *composeService) runPlugin(ctx context.Context, project *types.Project,
 		return err
 	}
 
+	mux.Lock()
+	defer mux.Unlock()
```
Comment (ndeloof) [inline pkg/compose/plugins.go:78]: We don't want providers to run sequentially, only the project mutation must be guarded by a mutex.

**Review by ndeloof — APPROVED** [review]
