### PR TITLE
check if a missing image won't be build via a service declared in depends_on section

### LINKED ISSUE #9983: [BUG] docker-compose: share same docker image built by a first service Regression or expected behaviour
### Description

I would like to share a docker image locally built by a first service between two services (the second one depends on the first one).

I was inspired by this stackoverflow thread: [How to prevent docker-compose building the same image multiple times?](https://stackoverflow.com/q/40899236/6267288).

While it was working fine on Ubuntu 22.04 LTS (ie: docker-compose builds the image for the first service and reuse it for the second service), it did not work on MacOS (ie: docker-compose builds the image for the first service and tries in the same time to load the image from a registry).

After investigating the issue, I found that the "issue" is from `docker-compose` application version.
It works fine with `docker-compose v1.x` but does not seem to work with `docker-compose v2.x`

### Steps To Reproduce

1. Create a simple example:

* Dockerfile:

```
FROM bash

RUN echo "Bonjour"
```

* docker-compose.yml

```
version: '3'

services:
  bonjour1:
    image: bonjour
    build:
      context: .

  bonjour2:
    image: bonjour
    depends_on:
      - bonjour1
```

2. Launch it with docker-compose `v1.29.2` (the one packaged for Ubuntu 22.04 LTS)

```
$ docker-compose up
Building bonjour1
Sending build context to Docker daemon  3.072kB
Step 1/2 : FROM bash
latest: Pulling from library/bash
9621f1afde84: Pull complete 
33d202a89164: Pull complete 
0c0490551894: Pull complete 
Digest: sha256:463b668dccc38f32a5bb5a5d59a3e1b787be432eb69b853fe4ad49cdce9a37d5
Status: Downloaded newer image for bash:latest
 ---> e6ec45344a58
Step 2/2 : RUN echo "Bonjour"
 ---> Running in fe8faee4d01d
Bonjour
Removing intermediate container fe8faee4d01d
 ---> 21484a6aa11c
Successfully built 21484a6aa11c
Successfully tagged bonjour:latest
WARNING: Image for service bonjour1 was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating test_docker_bonjour1_1 ... done
Creating test_docker_bonjour2_1 ... done
Attaching to test_docker_bonjour1_1, test_docker_bonjour2_1
test_docker_bonjour1_1 exited with code 0
test_docker_bonjour2_1 exited with code 0
```

3. Ensure the docker image is remove: `docker image rm -f bonjour`

4. Download latest version of `docker-compose` (ie: `v2.12.2`)

5. Launch it:

```
$ ~/Downloads/docker-compose up
[+] Running 0/2
 ⠿ bonjour1 Warning                                                                                                                                            2.5s
 ⠿ bonjour2 Error                                                                                                                                              3.1s
Error response from daemon: pull access denied for bonjour, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

### Compose Version

```Text
$ docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.6
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022

$ ~/Downloads/docker-compose version
Docker Compose version v2.12.2
```

### Docker Environment

```Text
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.0-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 8
  Running: 0
  Paused: 0
  Stopped: 8
 Images: 39
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-52-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.39GiB
 Name: olivier-ThinkPad-T480
 ID: CUNX:O35Z:RWB4:P23J:M2ON:I4WL:SQQG:ZHAG:5FBT:MAPE:4ORC:VKFB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Live Restore Enabled: false
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by glours**
Signed-off-by: Guillaume Lours <705411+glours@users.noreply.github.com>

**What I did**
Check if a missing image won't be build via a service declared in the `depends_on` section

**Related issue**
fixes #9983 

**(not mandatory) A picture of a cute animal, if possible in relation with what you did**
image

### CODE REVIEW

**Comment by glours** [comment]
I need to add an e2e test to finish this PR

File: pkg/compose/pull.go [hunk 1]
```diff
@@ -291,6 +291,22 @@ func (s *composeService) pullRequiredImages(ctx context.Context, project *types.
 	})
 }
 
+func isServiceImageToBuild(service types.ServiceConfig, services []types.ServiceConfig) bool {
+	if service.Build != nil {
+		return true
+	}
+	if service.DependsOn != nil {
```
Comment (ndeloof) [inline pkg/compose/pull.go:298]: I wonder we should require `depends_on` here (which has undefined behavior regarding build)
could just check all other services in the compose file for missing image

**Review by ndeloof — APPROVED** [review]

File: pkg/compose/pull.go (hunk 1 above)
Comment (glours) [reply pkg/compose/pull.go:298]: Right we can check if the `image` name is defined in a service with a `build` section

**Review by ndeloof — APPROVED** [review]

File: pkg/compose/pull.go [hunk 2]
```diff
@@ -291,6 +291,19 @@ func (s *composeService) pullRequiredImages(ctx context.Context, project *types.
 	})
 }
 
+func isServiceImageToBuild(service types.ServiceConfig, services []types.ServiceConfig) bool {
```
Comment (milas) [inline pkg/compose/pull.go:294]: This is beginning to look like Tilt code 😂

**Review by milas — APPROVED** [review]
