### PR TITLE
Swap to Reader in bake to avoid hangs on output

### LINKED ISSUE #12973: [BUG] Compose hangs on `load .dockerignore`
### Description

When I try to execute my previously-working compose file, the build hangs at
```
load .dockerignore
transferring context: 209B
```

It doesn't matter if I delete the contents of my .dockerignore, ignore the cache, etc. It also *does* work if I directly use `docker buildx build`.

This also happens if I set `COMPOSE_BAKE=true` or unset the environment variable.

### Steps To Reproduce

Unfortunately I haven't gotten to a minimal repro yet. This compose set up builds one image from a sibling directory and pulls the base image from a private docker repo in an AWS account. That said, given `buildx` has no trouble authenticating and pulling the image, and the sibling repo also builds without a problem, something else seems fishy here.

### Compose Version

```Text

```

### Docker Environment

```Text

```

### Anything else?

Here's the build log I have with `docker compose --verbose build`:

```
$ docker compose --verbose build
DEBU[0000] Enabled Docker Desktop integration (experimental) @ unix:///Users/ndscott/Library/Containers/com.docker.docker/Data/docker-cli.sock
DEBU[0000] bake build config:
{
  "group": {
    "default": {
      "targets": [
        "web",
        "web-ts"
      ]
    }
  },
  "target": {
    "web": {
      "context": "/Users/ndscott/code/mhealth-webapp",
      "dockerfile": "/Users/ndscott/code/mhealth-webapp/Dockerfile",
      "args": {
        "BUNDLE_WITHOUT": "",
        "IMAGE": "dev",
        "LOCAL_BUILD": "1"
      },
      "tags": [
        "mhealth-webapp-web"
      ],
      "platforms": [
        "linux/amd64"
      ],
      "output": [
        "type=docker,load=true,push=false"
      ]
    },
    "web-ts": {
      "context": "/Users/ndscott/code/docket-webapp",
      "dockerfile": "/Users/ndscott/code/docket-webapp/Dockerfile",
      "tags": [
        "mhealth-webapp-web-ts"
      ],
      "target": "development",
      "secret": [
        "id=docket-webapp-npmrc,type=file,src=/Users/ndscott/code/docket-webapp/.npmrc"
      ],
      "output": [
        "type=docker,load=true,push=false"
      ]
    }
  }
}
DEBU[0000] Executing bake with args: [bake --file - --progress rawjson --metadata-file /var/folders/80/bh48wswj3z3c75wyg0151blr0000gn/T/compose-build-metadataFile-1478244001.json --allow fs.read=/Users/ndscott/code/docket-webapp --allow fs.read=/Users/ndscott/code/mhealth-webapp]
TRAC[0000] Plugin server listening on /var/folders/80/bh48wswj3z3c75wyg0151blr0000gn/T/docker_cli_a51847eb2c076b7617e1c2a4869ce117
[+] Building 0.8s (10/24)
 => [internal] load local bake definitions                                                                                                                                          0.0s
 => => reading from stdin 962B                                                                                                                                                      0.0s
 => [web internal] load build definition from Dockerfile                                                                                                                            0.0s
 => => transferring dockerfile: 6.57kB                                                                                                                                              0.0s
 => [web-ts internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 5.13kB                                                                                                                                              0.0s
 => [web-ts internal] load metadata for docker.io/dockethealth/<redacted>                            0.5s
 => [web internal] load metadata for <redacted>.dkr.ecr.us-east-2.amazonaws.com/<redacted>:latest                                                                    0.6s
 => [auth] sharing credentials for <redacted>.dkr.ecr.us-east-2.amazonaws.com                                                                                                     0.0s
 => [auth] <redacted>:pull token for registry-1.docker.io                                                                                                       0.0s
 => [web-ts internal] load .dockerignore                                                                                                                                            0.0s
 => => transferring context: 104B                                                                                                                                                   0.0s
 => [web-ts base  1/10] FROM docker.io/dockethealth/<redacted>                                       0.0s
 => [web-ts internal] load build context                                                                                                                                            0.1s
 => => transferring context: 240.97kB                                                                                                                                               0.1s
 => [web internal] load .dockerignore                                                                                                                                               0.0s
 => => transferring context: 209B                                                                                                                                                   0.0s
DEBU[0005] otel error                                    error="<nil>"
```

The `otel error` consistently occurs after ~4 seconds.

### PR DESCRIPTION
**Pull request by nscott**
**What I did**

I reproduced a build problem where my build hangs for what was an unknown reason. This was due to the lack of handling an error - `compose build` should have crashed. Instead, it appeared like a hang. The root cause was really that we can't predict the size of output from `buildx bake`, so instead I swapped from a scanner with a hard buffer limit to a generic streaming reader.

**Related issue**

This fixes #12973 

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**

image

### CODE REVIEW

File: pkg/e2e/build_test.go [hunk 1]
```diff
@@ -580,3 +580,19 @@ func TestBuildSubDependencies(t *testing.T) {
 	out = res.Combined()
 	assert.Check(t, strings.Contains(out, "main  Built"))
 }
+
+func TestBuildLongOutputLine(t *testing.T) {
+	c := NewParallelCLI(t)
+
+	t.Cleanup(func() {
+		c.RunDockerComposeCmd(t, "-f", "fixtures/build-test/long-output-line/compose.yaml", "down", "--mri=local")
```
Comment (ndeloof) [inline pkg/e2e/build_test.go]:
```suggestion
		c.RunDockerComposeCmd(t, "-f", "fixtures/build-test/long-output-line/compose.yaml", "down", "--rmi=local")
```

Comment (nscott) [reply pkg/e2e/build_test.go]: 🥴 Fixed locally and force-pushed since GitHub buttons have bitten me in the past. Thanks for catching this!

**Review by glours — APPROVED** [review]
LGTM
