### PR TITLE
Wait and scale 0

### LINKED ISSUE #9149: Do not `--wait` for containers with `--scale` `0`
**Description**

`docker-compose up --wait` waits for containers scaled to `0`.

**Steps to reproduce the issue:**
1. Create a `docker-compose.yml` with the following content:
```
version: "3.8"
services:
  foo:
    image: alpine
    command: [ "/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait" ]
  bar:
    image: alpine
    command: [ "/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait" ]
```
2. Run `docker-compose up -d --scale=foo=0 --wait`.

**Describe the results you received:**
`docker-compose` will infinitely wait for `foo` to start.

**Describe the results you expected:**
`docker-compose` will wait only for `bar` to start and exit successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version 2.2.3
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
 Containers: 13
  Running: 12
  Paused: 0
  Stopped: 1
 Images: 47
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.843GiB
 Name: docker-desktop
 ID: MACJ:FSVR:FQR3:ZQDN:UMFZ:TTR2:KJR4:ITRP:ICW7:J6FI:4DHT:XCYJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

### PR DESCRIPTION
**Pull request by glours**
**What I did**
* During dependencies wait process, skip services with a scale property equals to 0 to avoid waiting indefinitely.
* Also fixed an early return in the wait process when reaching a dependency with a `service_started` condition, now the service is skipped and we continue with the rest of the dependencies
* Add tests for this 2 use cases

**Related issue**
fix #9149 

**(not mandatory) A picture of a cute animal, if possible in relation with what you did**
image

### CODE REVIEW

**Review by ndeloof — APPROVED** [review]

File: pkg/compose/convergence.go [hunk 1]
```diff
@@ -276,9 +276,10 @@ func (s *composeService) waitDependencies(ctx context.Context, project *types.Pr
 	eg, _ := errgroup.WithContext(ctx)
 	w := progress.ContextWriter(ctx)
 	for dep, config := range dependencies {
-		if config.Condition == types.ServiceConditionStarted {
-			// already managed by InDependencyOrder
-			return nil
+		if shouldWait, err := shouldWaitForDependency(dep, config, project); err != nil {
+			return err
+		} else if !shouldWait {
+			continue
```
Comment (ulyssessouza) [inline pkg/compose/convergence.go:282]: nit
```suggestion
		} 
		if !shouldWait {
			continue
```

File: pkg/compose/convergence.go [hunk 2]
```diff
@@ -334,6 +335,20 @@ func (s *composeService) waitDependencies(ctx context.Context, project *types.Pr
...
 }
 
+func shouldWaitForDependency(serviceName string, dependencyConfig types.ServiceDependency, project *types.Project) (bool, error) {
+	if dependencyConfig.Condition == types.ServiceConditionStarted {
+		// already managed by InDependencyOrder
+		return false, nil
+	}
+	if service, err := project.GetService(serviceName); err != nil {
+		return false, err
+	} else if service.Scale == 0 {
```
Comment (ulyssessouza) [inline pkg/compose/convergence.go:345]: nit
```suggestion
	}
	if service.Scale == 0 {
```

**Review by ulyssessouza — APPROVED** [review]
