### PR TITLE
Fix invalid path error when using OCI artifacts on Windows

### LINKED ISSUE #13572: [BUG] Compose with OCI artifacts is failing on Windows
### Description

I'm unable to launch Compose stacks on Windows machines that are sourced from OCI artifacts.

### Steps To Reproduce

1. Run command:

    ```bash
    docker compose -f oci://dockersamples/labspace-mcp-gateway config
    ```

See error:

```
CreateFile C:\Users\mikesir87\oci:\dockersamples\.env: The filename, directory name, or volume label syntax is incorrect.
```

### Compose Version

```Text
Docker Compose version v5.0.2
```

### Docker Environment

```Text
Client:
 Version:    29.2.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Docker AI Agent - Ask Gordon (Docker Inc.)
    Version:  v1.17.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-ai.exe
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.31.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v5.0.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.47
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  desktop: Docker Desktop commands (Docker Inc.)
    Version:  v0.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-desktop.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.31
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  mcp: Docker MCP Plugin (Docker Inc.)
    Version:  v0.38.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-mcp.exe
  model: Docker Model Runner (Docker Inc.)
    Version:  v1.0.8
    Path:     C:\Program Files\Docker\cli-plugins\docker-model.exe
  offload: Docker Offload (Docker Inc.)
    Version:  v0.5.42
    Path:     C:\Program Files\Docker\cli-plugins\docker-offload.exe
  pass: Docker Pass Secrets Manager Plugin (beta) (Docker Inc.)
    Version:  v0.0.24
    Path:     C:\Program Files\Docker\cli-plugins\docker-pass.exe
  sandbox: Docker Sandbox (Docker Inc.)
    Version:  v0.11.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sandbox.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.19.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 76
 Server Version: 29.2.0
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Discovered Devices:
  cdi: docker.com/gpu=webgpu
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: dea7da592f5d1d2b7755e3a161be07f43fad8f75
 runc version: v1.3.4-0-gd6d73eb8
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.87.2-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 15.37GiB
 Name: docker-desktop
 ID: d5353205-c6de-4882-bc73-dcd3460c1cb4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=npipe://\\.\pipe\docker_cli
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
 Firewall Backend: iptables
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mikesir87**
Resolves #13572 

And AI disclaimer - Claude performed the troubleshooting and fix in this PR.

I have built the Compose binary locally and validated the fix does work on my Windows machine.

## Problem                                 
                                                                                                                                                                                                                      
When using Docker Compose with an OCI artifact on Windows (e.g., `docker compose -f oci://dockersamples/welcome-to-docker up`), the following error occurred:                                                      
                                                                                                                                                                                                                    
```                                                                                                                                                                                                                
CreateFile C:\Users\username\oci:\dockersamples\.env: The filename, directory name, or volume label syntax is incorrect.                                                                                           
```                                                                                                                                                                                                                
                                                                                                                                                                                                                    
This error was introduced between v5.0.0 and v5.0.1, specifically by commit 6c043929a which fixed error handling in `setEnvWithDotEnv`. The bug existed in v5.0.0 but was silently ignored due to improper error   
handling.                                                                                                                                                                                                         
                                                                                                                                                                                                                    
## Root Cause                                                                                                                                                                                                      
                                                                                                                                                                                                                    
The issue occurred in the `setEnvWithDotEnv` function in `cmd/compose/compose.go`:                                                                                                                                 
                                                                                                                                                                                                                    
1. When `setEnvWithDotEnv` is called with an OCI artifact path, it creates ProjectOptions without registering any remote loaders                                                                                   
2. The compose-go library's `GetWorkingDir()` method doesn't recognize the path as a remote resource                                                                                                               
3. It tries to treat the OCI reference as a local file path by calling `filepath.Abs()` on it                                                                                                                      
4. On Windows, `filepath.Abs("oci://dockersamples/...")` produces an invalid path like `C:\Users\username\oci:\dockersamples`                                                                                      
5. When trying to load `.env` files, it appends to this malformed path, resulting in: `C:\Users\username\oci:\dockersamples\.env`                                                                                  
6. Windows rejects this path because colons are only valid after drive letters                                                                                                                                     
                                                                                                                                                                                                                    
### Code Flow                                                                                                                                                                                                      
                                                                                                                                                                                                                    
In compose-go's `cli/options.go`, the `GetWorkingDir()` method:                                                                                                                                                    
```go                                                                                                                                                                                                              
func (o *ProjectOptions) GetWorkingDir() (string, error) {                                                                                                                                                         
    if o.WorkingDir != "" {                                                                                                                                                                                        
        return filepath.Abs(o.WorkingDir)                                                                                                                                                                          
    }                                                                                                                                                                                                              
PATH:                                                                                                                                                                                                              
    for _, path := range o.ConfigPaths {                                                                                                                                                                           
        if path != "-" {                                                                                                                                                                                           
            for _, l := range o.ResourceLoaders {                                                                                                                                                                  
                if l.Accept(path) {                                                                                                                                                                                
                    break PATH  // Skip filepath.Abs for remote resources                                                                                                                                          
                }                                                                                                                                                                                                  
            }                                                                                                                                                                                                      
            absPath, err := filepath.Abs(path)  // BUG: Called for OCI paths when no loaders registered                                                                                                            
            if err != nil {                                                                                                                                                                                        
                return "", err                                                                                                                                                                                     
            }                                                                                                                                                                                                      
            return filepath.Dir(absPath), nil                                                                                                                                                                      
        }                                                                                                                                                                                                          
    }                                                                                                                                                                                                              
    return os.Getwd()                                                                                                                                                                                              
}                                                                                                                                                                                                                  
```                                                                                                                                                                                                                
                                                                                                                                                                                                                    
Without remote loaders registered, OCI paths fall through to `filepath.Abs()`, causing the issue.                                                                                                                  
                                                                                                                                                                                                                    
## Solution                                                                                                                                                                                                        
                                                                                                                                                                                                                    
Modified `setEnvWithDotEnv` to detect remote config paths and skip environment loading for them:                                                                                                                   
                                                                                                                                                                                                                    
```go                                                                                                                                                                                                              
func setEnvWithDotEnv(opts ProjectOptions) error {                                                                                                                                                                 
    // Check if we're using a remote config (OCI or Git)                                                                                                                                                           
    // If so, skip env loading as remote loaders haven't been initialized yet                                                                                                                                      
    for _, path := range opts.ConfigPaths {                                                                                                                                                                        
        if strings.HasPrefix(path, remote.OciPrefix) || strings.Contains(path, "://") {                                                                                                                            
            return nil                                                                                                                                                                                             
        }                                                                                                                                                                                                          
    }                                                                                                                                                                                                              
    // ... rest of the function unchanged                                                                                                                                                                          
}                                                                                                                                                                                                                  
```                                                                                                                                                                                                                
                                                                                                                                                                                                                    
This approach:                                                                                                                                                                                                     
- Detects remote config paths early (OCI: `oci://`, Git: URLs with `://`)                                                                                                                                          
- Skips the problematic .env loading for remote configs                                                                                                                                                            
- Allows normal processing for local compose files                                                                                                                                                                 
- Environment loading for remote configs happens later in the flow when remote loaders are properly initialized                                                                                                    
                                                                                                                                                                                                                    
## Testing                                                                                                                                                                                                         
                                                                                                                                                                                                                    
- Added tests in `cmd/compose/compose_oci_test.go` for OCI artifacts, Git remotes, and local paths                                                                                                                 
   - Verified fix works on Windows ARM64                                                                                                                                                                              
   - All existing tests pass                                                                                                                                                                                          

## Files Changed                                                                                                                                                                                                   
                                                                                                                                                                                                                      
- `cmd/compose/compose.go`: Modified `setEnvWithDotEnv` function                                                                                                                                                   
- `cmd/compose/compose_oci_test.go`: Added tests for the fix"

### CODE REVIEW

**Comment by thaJeztah** [comment]
⚠️ canned reply ahead ⚠️ 

Thank you for contributing! It appears your commit message is missing a DCO sign-off,
causing the DCO check to fail.

We require all commit messages to have a `Signed-off-by` line with your name
and e-mail (see ["Sign your work"](https://github.com/moby/moby/blob/v20.10.11/CONTRIBUTING.md#sign-your-work)
in the CONTRIBUTING.md in this repository), which looks something like:

```
Signed-off-by: YourFirsName YourLastName <yourname@example.org>
```

There is no need to open a new pull request, but to fix this (and make CI pass),
you need to _amend_ the commit(s) in this pull request, and "force push" the amended
commit.

Unfortunately, it's not possible to do so through GitHub's web UI, so this needs
to be done through the git commandline.

You can find some instructions in the output of the DCO check (which can be found
in the "checks" tab on this pull request), as well as in the [Moby contributing guide](https://github.com/moby/moby/blob/v20.10.11/docs/contributing/set-up-git.md).

Steps to do so "roughly" come down to:

1. Set your name and e-mail in git's configuration:

    ```bash
    git config --global user.name "YourFirstName YourLastName"
    git config --global user.email "yourname@example.org"
    ```

    (Make sure to use your _real_ name (**not your GitHub username/handle**) and e-mail)


2. Clone your fork locally
3. Check out the branch associated with this pull request
4. Sign-off and amend the existing commit(s)

    ```bash
    git commit --amend --no-edit --signoff
    ```

    If your pull request contains multiple commits, either squash the commits (if
    needed) or sign-off each individual commit.

5. _Force push_ your branch to GitHub (using the `--force` or [`--force-with-lease`](https://stackoverflow.com/questions/52823692/git-push-force-with-lease-vs-force) flags) to update the pull request.


Sorry for the hassle (I wish GitHub would make this a bit easier to do), and let me know if you need help or more detailed instructions!

File: cmd/compose/compose.go [hunk 1]
```diff
@@ -678,6 +678,17 @@ func stdinfo(dockerCli command.Cli) io.Writer {
 }
 
 func setEnvWithDotEnv(opts ProjectOptions) error {
+	// Check if we're using a remote config (OCI or Git)
```
Comment (ndeloof) [inline cmd/compose/compose.go:681]: this should use opts.remoteLoaders, if one of those Accept the config path, then resource is remote

Comment (mikesir87) [reply cmd/compose/compose.go:681]: Ok! Just pushed a change that uses opts.remoteLoaders

**Review by ndeloof — APPROVED** [review]
